### ISSUE TITLE
Ambigious definition 

### ISSUE THREAD

**Issue by jdIBM** [ibm-cloud-docs/vmwaresolutions#952] opened 2020-04-28 18:36 UTC
Can you use the BYOL feature for some VMware components and purchase monthly licenses for others?

Yes. You can use the BYOL feature or purchase licenses for any combination of the four VMware components. The IBM Cloud for VMware Solutions console makes it straightforward for you to select the licensing option when you order your instance. Your licensing option at the time of initial instance order applies for the lifetime of that instance.

-Scott moonen We don’t support a mix within a cluster but we do support a mix from cluster to cluster.

The Answer, should clarify that a VCS Instance can have mixed however a Chile Cluster cannons use mixed licensing sources

**Comment by jdIBM** [comment] 2020-04-28 18:36
https://cloud.ibm.com/docs/vmwaresolutions/vmonic?topic=vmware-solutions-faq_byol#faq_byol-mthly-license

**Comment by jdIBM** [comment] 2020-04-28 18:36
Also this page shouldn't be listed under vmonic as that is SAP specific

**Comment by delia-rusu** [comment] 2020-04-29 18:39
Thanks for your feedback! 
1) This is a duplicate of https://github.ibm.com/Bluemix/Documentation-content/issues/8219. Let's use 8219 for tracking purposes.
2) The name vmonic is just internal, the external path/URL is https://cloud.ibm.com/docs/vmwaresolutions?topic=vmware-solutions-faq_byol.
Setting redirects for all our topics is time-consuming and low priority right now.

**Closed by delia-rusu** 2020-04-29 18:39 UTC
